/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(cufft.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(aee0f9577329fd898b226a89b08137a2)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cuda/cufft.h>
// pydoc.h is automatically generated in the build directory
#include <cufft_pydoc.h>

void bind_cufft(py::module& m)
{

    using cufft    = gr::cuda::cufft;


    py::class_<cufft, gr::tagged_stream_block, gr::block, gr::basic_block,
        std::shared_ptr<cufft>>(m, "cufft", D(cufft))

        .def(py::init(&cufft::make),
           D(cufft,make)
        )
        



        ;




}








