/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(Multi_Channel_DDC.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(b5a9681a068d406f48c75a7f48fc4d97)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cuda/Multi_Channel_DDC.h>
// pydoc.h is automatically generated in the build directory
#include <Multi_Channel_DDC_pydoc.h>

void bind_Multi_Channel_DDC(py::module& m)
{

    using Multi_Channel_DDC    = gr::cuda::Multi_Channel_DDC;


    py::class_<Multi_Channel_DDC, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<Multi_Channel_DDC>>(m, "Multi_Channel_DDC", D(Multi_Channel_DDC))

        .def(py::init(&Multi_Channel_DDC::make),
           D(Multi_Channel_DDC,make)
        )
        



        ;




}








